### ISSUE TITLE
Install Monterey 12.2 Failure

### ISSUE THREAD

**Issue by ArthurJLewis** [seven-of-eleven/designare-z390-opencore-efi#58]
Towards the bottom of output after boot from "Macintosh HD" getting
"Checkpoint Monitor Failure 1 (0x1183)" followed a little later by "We don't support SMC on this platform". 
At least it reverts back to Big Sur 11.2.

There are others after googling that have reported the same issue.

Don't currently have logs but will go after that tomorrow.

Have F9i BIOS on a Gigabyte Designare Z390 with Intel i9-9900k, BIOS configured as per your guide.
Currently running Big Sur 11.2 without a problem.
Used your EFI directly with just the SMBIOS changes.

Using Samsung 970 EVO 500GB NVMe drives for MacOS (APFS). Another one of these drives has Win11 on it without a problem for dual boot.

GPU is Gigabyte AORUS Radeon RX 5700 XT 8GB (GV-R57XTAORUS-8GD)

Any clues, has anyone else seen this issue.

As an aside:

 I have Monterey 12.1 running nicely via VMware's ESXi Type 1 Hypervisor on a host server and it was very straightforward to get up and running.  For home use you can get a free license to use it. The only issue I have with it right now is that I currently don't have audio if I play a video etc. on a client.  However the beauty of this is that I can have multiple VMs on the server and run them all on a client, so MacOS, Ubuntu and Win11 without having to reboot.

Another Type 1 Hypervisor is Proxmox which is open source but I haven't got around to playing with it.

Thanks so much for your guides.

Arthur

**Comment by seven-of-eleven** [comment]
@ArthurJLewis not sure if you've resolved this issue? Other reports online outline the following:
```
You just have to have SecureBootModel in config.plist set to “Disabled” instead “Default” during installation (assuming you’re using OpenCore boot loader). Have fun with Monterey 😀
```
After the install I would change `SecureBootModel` back to `Default`.  Hope this helps.
