### ISSUE TITLE
Internet has stopped working

### ISSUE THREAD

**Issue by jordanurbs** [seven-of-eleven/designare-z390-opencore-efi#59]
**Describe the bug**
Not sure how this happened, but it happened gradually. I use predominantly Ethernet for internet. It started a few weeks ago, when I would have to toggle active/disabled the Ethernet service in order to get the internet running again. Prior to this, Network system preferences does not show an issue. Once I restart the service it says "Self-Assigned IP" after "Not Connected" for a bit.  At first, it would finally turn green and connect after a few minutes. But now, it just stays yellow.

Running 11.6 Haven't run any upgrades or hardware changes. Also having issues with Pro apps, sometimes the previews don't display after changing parameters. Not sure if it's related but in general I'm feeling like the computer is "decaying" without reason.

**Hardware Specifications:**
Using APFS formatted hard drives. Same hardware as repo.

Any clue what's happening?

**Comment by baughmann** [comment]
Strange, I cannot say I have a guess. I should probably update kexts and drivers at this point. Maybe doing this manually will have an impact? 

I responded to your DM regarding the Fenvi, BTW.

**Comment by Kgrem** [comment]
If you redo the patch with command ~undo it Should by working

**Comment by seven-of-eleven** [comment]
I know this issue is a little old. So I'm not sure if it's still relevant. The latest EFI and kexts should resolve the Networking issues. Both LAN ports are currently working for me. Let me know otherwise. Thanks.
