### ISSUE TITLE
Installation Process

### ISSUE THREAD

**Issue by bennydf123** [seven-of-eleven/designare-z390-opencore-efi#60]
Hello,

Noob question but I have stuffed up my current setup I changed my BIOS settings I'm on F9b copied the new EFI onto my hard drive and had the USB boot ready to go and it had a loading error wouldn't go past my system BIOS. I'm now going to take out my SSD drive that was running and revert back to the old EFI on Mojave.

For future install how do I go about updating my system with the new EFI is it a case of updating from the old computer and then copying the new EFI in?? Please let me know on the best way to install

**Comment by baughmann** [comment]
@bennydf123  Have you tried F9 (the official release)? **Beware, that according to some you cannot revert back after updating to this version.**

I'm assuming it's a BIOS issue. I had a problem with the installer not going past the Apple logo when I didn't have CFG Lock off, or when CSM support was not enabled.

**Comment by bennydf123** [comment]
I tried the F9 official release F9i which is the recommended BIOS system in the instructions. I formatted my drive and it is now visible in the BIOS but when I choose to boot from it says '"Halting on Critical Error"

**Comment by baughmann** [comment]
@bennydf123 F9 is a release whereas F9i was a beta, IIRC

**Comment by bennydf123** [comment]
Okay but it says in the instructions that F9i has to be the version that I use. The halting on critical error is the EFI in the partition map to the USB.

**Comment by bennydf123** [comment]
I've done all the necessary steps and I'm sure it's a problem with the installer being in 12.2 instead of 12.1 is there anyway I could be provided with a link? The only other version I can find is of Big Sur which might not work with the current EFI

**Comment by bennydf123** [comment]
Another UPDATE I have just got to this after getting Monterey to install page as per normal gets to around 13 mins to install and then I get the screen going black with this log fil
[opencore-2022-02-21-035147.txt](https://github.com/baughmann/designaire-z390-intel-i9-9900k-opencore/files/8106165/opencore-2022-02-21-035147.txt)
e

**Comment by seven-of-eleven** [comment]
@bennydf123 did you get to the install? Let me know if you're still having issues, otherwise I'll close this. Thanks.

**Comment by bennydf123** [comment]
Did the new install but get an error message like a stop sign with apple and then it says to go to their support page

**Comment by bennydf123** [comment]
EDIT ADD THIS TO THE INSTRUCTIONS ON THE MAIN PAGE

If it opens up as Russian go into terminal and type:
nvram -c and hit enter
shutdown -r now

**Comment by seven-of-eleven** [comment]
@bennydf123 this could be due a couple of different things:
1. BIOS setting - check to ensure they are set correctly - generally reported around SecureBoot issues - you can try set `SecureBootModel` to `Disabled`
2. NVME drive issues - certain NVME drives are reported as unsupported or require config.plist changes (can try `SetApfsTrimTimeout = 0`)
3. Fresh install vs. upgrade - if you're performing an OS upgrade the UEFI>APFS `MinDate` and `MinVersion` values may need to be changed to `-1`

Can you provide an error / install log?
What Monterey version are you trying to install?

**Comment by bennydf123** [comment]
Update successfully installed. Had to format disk to APFS rather than Mac OS Journaled in the formatting stage. Then at the 12 min mark it restarted as usual, this time I took the SSD out re copied the EFI and it booted.

What's not working is wifi with my Fevi receiver however; bluetooth is.

**Comment by seven-of-eleven** [comment]
For wifi you may need to set `DisableIoMapper` to `True` as discovered here #67
Let me know if that solves the wifi issue.

**Comment by bennydf123** [comment]
Problem solved cheers!
