### ISSUE TITLE
Thunderbolt not working with bios F9/OSX12/OSX11 only with OSX10.x (using a MOTU Pro audio interface )

### ISSUE THREAD

**Issue by fab672000** [seven-of-eleven/designare-z390-opencore-efi#62]
**Describe the bug**
Thunderbolt not working, does not seem to be detected at all

**OpenCore Logs**
none yet, will populate

**Expected behavior**
thunderbolt audio should be detected by Monterey latest version.

**Screenshots**

**Hardware Specifications (please complete the following information):**
 - CPU: Intel Core i9 9900k
 - GPU: AMD Radeon RX580
 - Motherboard: Designaire Z390
 - Storage: Crucial M2 drives

**Additional context**
Everything else so far worked well.
Using Designare F9 BIOS+ Core-i9 9900k + Radeon Sapphire RX580 GFX
Applied your instructions and double-checked several times all your BIOS settings were applied, installed TB latest drivers for my audio interface (was working in Catalina with Clover)
TB works fine in my WIndows 10 partition
![tb no driver](https://user-images.githubusercontent.com/6124901/158458105-ac6f163a-a570-40dc-bf52-03c6954d8c91.png)
![sysinfo](https://user-images.githubusercontent.com/6124901/158458121-9e327de8-03c2-4fb5-a91b-c4536db4f34f.png)

Using your EFI folder with only minimum changes to config.plist as recommended in your instructions.

**Comment by djxray89** [comment]
I'm currently having this same exact issue as well. I have Same CPU,GPU ,MOBO on F9 Bios, on Opencore 7.8

**Comment by fab672000** [comment]
Also tried with bioses F6, F9i, F9i with latest microcode patches all failed on BigSur / Monterey, works fine on Catalina.

**Comment by tinnakis** [comment]
Hello and sorry if my question is not related to the subject. Please tell me how did you downgrade your bios from F9 to F6, F9i? Thank you very much!

**Comment by fab672000** [comment]
> Please tell me how did you downgrade your bios from F9 to F6, F9i? 
Used the fptw64.exe  intel tool.

Instrucions:
1. Download the correct FPT tool for your motherboard and create a folder on C Drive called FPT. Copy the contents of the WIN64 folder from the zip archive into the new FPT folder on C Drive.

2. Open an elevated command prompt (as administrator) and navigate to the FPT folder

3. Make a backup of your current BIOS chip using the command;

fptw64 -d bios.bin

You should see "FPT Operation Successful." If not then you may have a BIOS chip that FPT cannot recognise.

4. To check if your motherboard has any Intel ethernet adapters and at the same time backup the MAC address(es) type the following commands;

fptw64 -gbe -d gbe.bin

a. There are only six Z370/Z390 motherboards that don't have an Intel NIC, for those you will see the following;

"GbE region does not exist!"

This means you likely have either a Realtek or Rivet Networks 'Killer' NIC and don't need to worry about your MAC being erased by FPT.

b. All other Z370/Z390 motherboards that have Intel Gigabit Ethernet Adapters should give you the following message;

8KB of 8KB - 100 percent complete.
FPT Operation Successful.

NOTE: If you open gbe.bin in a hex editor you can find your MAC address(es).

5. Copy the BIOS file you want to flash into your FPT folder.

Use the following commands to flash the entire EEPROM (all BIOS regions are overwritten i.e. Descriptor, GbE, ME and BIOS);

fptw64 -SAVEMAC -f <DowngradeBIOSName>.bin

The command -SAVEMAC will retain your Intel MAC address(es) so don't leave it out!

If you have a motherboard with no Intel NIC then you can just use;

fptw64 -f <DowngradeBIOSName>.bin

6. Once the flash operation says it has completed successfully type the following command to IMMEDIATLEY reboot and load the BIOS you just flashed;

fptw64 -greset

Note that your PC will restart instantly without any warning as though you have pressed the reset button.

7. Go into BIOS and check the BIOS version under System Info, it should be the older BIOS.

**Comment by tinnakis** [comment]
Thank you. I have the same Gigabyte Z390 Designare

**Comment by matteofreddi** [comment]
Hi, same problem here, with Blackmagic design thunderbolt device, any news on this topic?

**Comment by fab672000** [comment]
Try enabling apple VTD (which also means you need to activate intel virtualization in BIOS).

**Comment by matteofreddi** [comment]
Hi, with Vt-d I can finally use thunderbolt devices! But both Ethernet controllers does not work.. 🤦🏻‍♂️

**Comment by tinnakis** [comment]
> 

HI, could you please tell me what bios version you are using. Thanks.

**Comment by matteofreddi** [comment]
Sure, I’m using F9i

**Comment by seven-of-eleven** [comment]
@matteofreddi I just started playing around with the EFI to include Thunderbolt. Looks like you have it figured out? Was there anything in addition to the Vt-d changes to enable it? 

If more was needed can you share your EFI folder (remove serial numbers), so I can compare?

Thanks for your help. Haven't had any Thunderbolt devices to test things on until now.

**Comment by seven-of-eleven** [comment]
Latest version of EFI support Thunderbolt. Let me know if I need to change any settings as I only had one Thunderbolt devices to test with. Thanks.
