### ISSUE TITLE
Is anyone taking over Nick's work?

### ISSUE THREAD

**Issue by jiribanas** [seven-of-eleven/designare-z390-opencore-efi#63]
Nick has done a great job creating and maintaining this repo and I can't thank him enough. 

I'm running the latest EFI with macOS 12.4 and so far all upgrades were smooth and easy. My BIOS is F9 and I have the exact same hardware as Nick. In fact, Nick's repo was the reason why I bought this particular hardware. 

I have four MacBook Pro and a Mac Studio so I don't have a shortage of real Macs. But I would like to keep this 2.5-year-old Hackintosh running too. Is anyone taking over Nick's work? Forking the repo and continuing to update the EFI? macOS 13 is coming out soon and there will be changes needed to support it. I don't have the skills or experience but I am happy to contribute financially to the continuous research and development of this EFI.

**Comment by jahwookie** [comment]
Seconding your motion that Nick did an impeccable job herding a network of
cats he never even met personally.

I broke down and bought a Mac Studio Max for audio processing, but am still
using the way overpowered Intel Hackintosh as a network file server.

I would say, and have said, that the future of running Mac OS on third
party hardware is in virtualization. Would love to hear anyone's take on
this. Best, JW

**Comment by seven-of-eleven** [comment]
@baughmann I'll take over the repo if you're still looking for someone. I'm not a hackintosh expert by any means. I have a couple other laptop repos available. I have similar hardware that I use daily. Z390 Designaire motherboard, RX 5700 XT, 64GB RAM, a bunch of drives. Currently running OC 0.8.2 and Monterey 12.5.  I don't use/have any thunderbolt devices so I can't test that part. My existing EFI folder is similar to yours (though I haven't compared the config.plist files). If you prefer to keep it, or pass it to someone else, no worries.

All the best.

**Comment by baughmann** [comment]
@seven-of-eleven Say no more! We can give the community a few days to chime in, but I'd assume there will be no objects. I will transfer it to you Friday evening or so EST I can transfer it to you if you have not changed your mind.

**Comment by seven-of-eleven** [comment]
@baughmann That sounds good to me. I have no plans to charge for this or my other repos. I'll maintain them as long as I have the hardware. I'm doing the updates anyways for myself. Sharing the end result is minimal compared to the amount of work others in this community are doing. I'm happy to help where I can.

Again if you prefer to maintain ownership or give it to someone else base on community feedback, I'll be happy to just fork the repo and submit pull requests.

**Comment by baughmann** [comment]
@seven-of-eleven Sorry for the delay, got distracted. You still want the repo?

**Comment by seven-of-eleven** [comment]
Yes. I'll still take it on. Whenever you're ready.

**Comment by baughmann** [comment]
@seven-of-eleven I've initiated the transfer request. Check your email. Ignore the "collaborator" one. I mistakenly sent that. Also, we should probably think about moving both this thread and the "General Discussion" thread over to the discussions tab now that it's available.

**Comment by jahwookie** [comment]
Thanks for all your friendly, on-point assistance, Nick. Best wishes in all
you do. John W.
