### ISSUE TITLE
Airplay Mirroring Black Screen on the output device

### ISSUE THREAD

**Issue by magnificent3** [seven-of-eleven/designare-z390-opencore-efi#64]
Hi there,

I used your EFI.

I have a SMBIOS iMacPro1,1 where I have the following configuration

Core i7 9700
dGPU + iGPU
MSI Armor RX 580 8GB
Asus PRIME Z390-M PLUS

I have everything working except for mirroring, and of course, sidecar.

Airplay Video works fine and DRM also works fine.
The only thing that isn't working is Airplay Mirror.

Do you have any thoughts that could help?

**Comment by seven-of-eleven** [comment]
@magnificent3 could be a hard issue to trouble shoot. Many real macs have the same issue. It can be anything from networking, needing an iOS update, or BIOS settings, to DRM issues. I have a similar issue on my computer. Airplay Video works great but Mirroring or Extended Display fails, oddly it works great on from my laptop hack (Lenovo X1C7). Sorry I can't help further but let me know if you've figured anything out.
