### ISSUE TITLE
No ethernet and WiFi  

### ISSUE THREAD

**Issue by jiribanas** [seven-of-eleven/designare-z390-opencore-efi#67]
I’ve been using Nick’s original EFI for 2+ years but I wanted to try your latest release with the upgraded OC. Initially, I kept my original SMBIOS for iMac and my own USBPorts.kext but the system couldn’t  connect via Ethernet nor WiFi. Bluetooth oddly works fine though. Then, I tried to swap my SMBIOS for a new one for MacPro like is in your EFI and also used your USBPorts.kext but got the same result. Nick’s previous release works for me. 

I have the exact same hardware as Nick used to have but for network I use the Fenvi 919 card. I know you mentioned in the readme that no Bluetooth and WiFi stack is included but since the Fenvi uses a native chip, macOS should recognize it as is.

There is another similar EFI for z390 Designare on GitHub that I have tried and that one works fine with my setup. I’d like to keep using yours though because it’s more “vanilla”. How to enable Fenvi 919 with your EFI? The guide your refer to in the readme isn’t specific to this card and it’s difficult for me to follow. 

Thank you in advance.

**Comment by seven-of-eleven** [comment]
Hi @jiribanas this is very interesting to me. Also strange that **non** of your networking works. I compared the last release to this one and there are only a couple differences. I have a few questions/suggestions for you to narrow down the issue:

1. Do you know if you have VT-D disabled in your BIOS? **If you don't**, you should set DisableIoMapper to `True`. I see this changed between releases. This has been [reported in the past to affect wifi](https://www.reddit.com/r/hackintosh/comments/owpshg/comment/h7hndce/?utm_source=share&utm_medium=web2x&context=3).
2. Which OS version are you on? If using BigSur you may need a different kext for the I211 LAN port (or non at all). You can disable the AppleIGB.kext to see if that helps.
3. Did you disable the RestrictEvents.kext? I don't think this would affect anything but if using SMBIOS iMac19,1 then you can disable it.
4. Did you try reset the NVRAM (you may have to hit space bar at the OpenCore picker screen to see the option)?

I've attached an EFI for you to try. It has DisableIoMapper set to True, SMBIOS iMac19,1 and I disabled the RestrictEvents and AppleIGB.kext.  Let me know if this changes anything on your end.

[EFI.zip](https://github.com/seven-of-eleven/designare-z390-opencore-efi/files/9291817/EFI.zip)

**Comment by jiribanas** [comment]
Thank you for your prompt reply. The attached EFI with my SMBIOS works well. I'll keep it running for a full work day to see if there are any hidden issues but Fenvi is working as expected. I would be curious to try your iMacPro one but first need to figure out why the original release EFI didn't work with my Fenvi.

Here are answers to your questions:

1. VT-D is disabled in my BIOS.
2. I am running macOS Monterey 12.5
3. I disabled RestrictEvents.kext when I made the attempt to use iMac 19,1 SMBIOS from the previous Nick's release. I enabled it when I tried your default MacPro one. Both rendered the same results, e.g. Fenvi not working.
4. I have not tried that, but I would like to try your released EFI with MacPro SMBIOS again and will see if that helps.

**Comment by jiribanas** [comment]
I have an update. I took a fresh copy of your released EFI and generated a new SMBIOS for MacPro7,1. Then I played with each change you made above and it turns out the culprit is `DisableIoMapper`. VT-D is indeed disabled but without `DisableIoMapper = True`, no network would work for me. With that change, it's running now. I'll keep it running for this week to see if there aren't any glitches.

**Comment by seven-of-eleven** [comment]
@jiribanas Thanks for your help with this. I'll note the fix and update the setting in the EFI. Let me know if there are any other glitches.
