### ISSUE TITLE
Rebooting after apple logo

### ISSUE THREAD

**Issue by spaumx** [seven-of-eleven/designare-z390-opencore-efi#68]
I use this configuration on my motherboard, but my computer restarts as soon as I see the apple logo. What to do?

**Comment by seven-of-eleven** [comment]
1. Check that your bios settings are correct.
2. Turn on verbose mode by adding `-v` to the `boot-args` key in the config.plist file. 
3. Post the error message from verbose (-v above) and log file to get an idea what's going wrong.

What OS version are you trying to install?
