### ISSUE TITLE
Ethernet does not work

### ISSUE THREAD

**Issue by mbiedzki** [seven-of-eleven/designare-z390-opencore-efi#69]
Hi, I am long time user of Nick's EFI, I decided to upgrade and start using ethernet.

Ethernet does not work.
In network preferences ethernet is recognized.
In system report ethernet en3 is recognized.
Connection via ethernet cable does not work, cable is verified, connects other equipment.

BIOS: F9i
All settings verified against your profile.
Recent EFI

Hardware Specifications
 - CPU: 3,6 GHz 8 core processor Intel Core i9
 - GPU: Radeon RX 580 4  GB
 - Motherboard: Designaire Z390
 - Storage:WDC WDS100T2B0C-00PXH0 APFS

**Comment by seven-of-eleven** [comment]
Are both ports not working? 
What OS version are you using? 

BigSur requires a different kext for the one port(I plan to include in the next release).

You may also need to set DisableIOMapper to true per #67

**Comment by mbiedzki** [comment]
Hi, thanks for your time and help, but en error was on my side. I had second EFI with old data on one of the disks and it was booting from it. So it was not reading your EFI at all.
Now everything works very well.

Best regards,
Michał
