### ISSUE TITLE
Boot & Hot Swap in F9i

### ISSUE THREAD

**Issue by hitindags** [seven-of-eleven/designare-z390-opencore-efi#72]
Your BIOS settings prevent me from booting in F9i. I have not figured out why, so I switched back to my original settings.

Also, would be nice if you added the SATA hot swap setting to your BIOS config. Needs to be enabled to work in macOS. Thank you!

**Comment by baughmann** [comment]
@hitindags thanks for reporting this

Do you know what specific settings in the included BIOS config prevent you from booting? Also, which EFI were you trying? Were you able to boot that EFI using your own BIOS config? What specific symptoms were you seeing when it failed to boot?

It will be difficult for anyone to trouble shoot this with the info your provided.

**Comment by hitindags** [comment]
Thank you for your reply. I think for now I'm going to stick to my previous config since it works and the maintainer mentioned that he will update the BIOS settings section some time soon.

**Comment by hitindags** [comment]
I Managed to fix the BIOS settings. For some reason, it's working now. What remains is the trouble with SATA hot swap. Here's a guide on how to fix this in Clover. I'm guessing the procedure in OC is similar:

To enable hot plug of any internally-connected SATA drive(s) please follow this procedure:
Individually enable the Hot Plug function for each desired SATA port. This is done from BIOS --> Peripherals --> SATA --> Hot Plug.
Add the following Kext patch using Clover Configurator --> Kernel and Kext Patches:
Name*: AppleAHCIPort
Find* [HEX]: 40600200
Replace* [HEX]: 00000000
Comment: SATA Hot Swap I/O Error Fix
![HotSwapPatch](https://user-images.githubusercontent.com/77179463/200847226-0433b559-c852-4be5-b3be-633d413bb734.jpg)

**Comment by hitindags** [comment]
This code seems to work:
<dict>
                    <key>Arch</key>
                    <string>Any</string>
                    <key>Base</key>
                    <string></string>
                    <key>Comment</key>
                    <string>SATA Hot Swap I/O Error Fix</string>
                    <key>Count</key>
                    <integer>1</integer>
                    <key>Enabled</key>
                    <true/>
                    <key>Find</key>
                    <data>QGACAA==</data>
                    <key>Identifier</key>
                    <string>com.apple.driver.AppleAHCIPort</string>
                    <key>Limit</key>
                    <integer>0</integer>
                    <key>Mask</key>
                    <data></data>
                    <key>MaxKernel</key>
                    <string></string>
                    <key>MinKernel</key>
                    <string></string>
                    <key>Replace</key>
                    <data>AAAAAA==</data>
                    <key>ReplaceMask</key>
                    <data></data>
                    <key>Skip</key>
                    <integer>0</integer>
                </dict>
