### ISSUE TITLE
Mac Automatic Updates no longer pulling latest MacOS version?

### ISSUE THREAD

**Issue by arashster** [seven-of-eleven/designare-z390-opencore-efi#76]
Is anyone facing an issue where OS won't update to the latest MacOS version via System Preferences -> General -> Software Update?

I've had to manually download Mac OS 13.5 to upgrade (from 13.4.1).

**Comment by seven-of-eleven** [comment]
I've noted that I have to disable the BlueToolFixup.kext before upgrading. I follow the following process when notified an update is available and I want to install it:
1. Mount EFI folder and disable BlueToolFixup.kext in the config.plist file.
2. Reboot with BlueToolFixup.kext disabled.
3. Upgrade through the System Settings.
4. Once upgrade is complete, mount EFI folder and enable BlueToolFixup.kext.
5. Reboot.

Hope this helps.
