### ISSUE TITLE
Greetings and thanks; does your setup support wake-on-lan (WOL)

### ISSUE THREAD

**Issue by xenophon61** [seven-of-eleven/designare-z390-opencore-efi#77]
Hi, and greetings from Athens.

I've had trouble with my (similar) setup as of Ventura 13.5 - IntelMausi stopped responding to WOL packets (and its LEDs are off when sleeping).

Tried your EFI (ACPI and all), but without success, even after upgrading to F9 BIOS. 

Must say that your write-up was very helpful, esp. in terms of AppleVTD (to which I was oblivious), but also overall - excellent job, thanks!

Quick question: does your rig wake with ethernet WOL packets?

TIA

Xen

**Comment by xenophon61** [comment]
Duh! 

Found out that in the F9 BIOS screen, there is a separate "NIC configuration" button individually under each en device, and one has to apply the "Wake-on-LAN enable" setting there, for a total of four (!) setting changes.

Sure enough, that fixed the issue ;-)

I apologize for taking so much of your time. Thanks for responding!

With greetings from Athens,

Xen

**Comment by seven-of-eleven** [comment]
Glad to hear you figured it out. Appreciate you posting the solution. 

Oddly I have one port working and the other not. I haven't checked my BIOS yet for the settings you mentioned above. It's not urgent for me but if I need it I now know how to fix.

Thanks and the best.
