### ISSUE TITLE
GPU Acceleration Not Working

### ISSUE THREAD

**Issue by bennydf123** [seven-of-eleven/designare-z390-opencore-efi#81]
Having issues with Dropbox, Splice, Playonmac and sometimes Adobe. 

GPU: AMD Radeon 580x.

**Comment by seven-of-eleven** [comment]
Hi @bennydf123 What OS are you using? Any other details you can provide? Could it be another program you have installed?

**Comment by bennydf123** [comment]
OS 14.3.1 The two programs which aren't working are dropbox and splice now. But it's certainly a GPU issue and I'm not sure how other programs could be affecting it when terminal boot shows that no other programs are interfering.

**Comment by seven-of-eleven** [comment]
Did you remove the boot-args (agdpmod=pikera) I have in the EFI for the 5700xt?

**Comment by bennydf123** [comment]
I'll do that now. In the meantime here is the code for what I got in terminal

benmason@Bens-iMac ~ % /Applications/Splice.app/Contents/MacOS/Splice 
[1164:0410/151307.034398:ERROR:crash_report_database_mac.mm(634)] open lock /Users/benmason/Library/Application Support/com.splice.Splice/Crashpad/pending/dc5db180-36e1-440f-a970-ac75c7d5bbc0.dmp: Resource temporarily unavailable (35)
15:13:07.074 [INFO] [pid=1164] ui-main - UI version: 5.0.11
15:13:07.301 [INFO] [pid=1164] ui-main - Connecting to bridge { port_range: [ 56765, 56785 ] }
15:13:07.531 [INFO] [pid=1164] ui-main - Initializing minimal LaunchDarkly client just for auth
sysctl: unknown oid 'sysctl.proc_translated'
15:13:07.741 [INFO] [pid=1164] ui-main - process arch x64
15:13:07.741 [INFO] [pid=1164] ui-main - machine arch x64
15:13:07.741 [INFO] [pid=1164] ui-main - feed url: https://api.splice.com/v2/desktop/darwin/stable/latest?v=5.0.11&architecture=x64
15:13:07.746 [ERROR] [pid=1164] ui-main - Attempting to read flag value before LaunchDarkly has been initialized
15:13:07.761 [INFO] [pid=1164] ui-main - initializing auth0 auth manager
15:13:07.761 [INFO] [pid=1164] ui-main - initializing offline auth manager
(node:1164) Warning: app.proto not found in any of the include paths /Applications/Splice.app/Contents/Resources/app.asar/managers/helper/../../../../../core/proto/
(Use `Splice --trace-warnings ...` to show where the warning was created)
server created on port 57766
15:13:07.778 [INFO] [pid=1164] ui-main - Splice Helper path: /Applications/Splice.app/Contents/Resources/Splice Helper.app/Contents/MacOS/Splice Helper from /Applications/Splice.app/Contents/Resources/app.asar/managers/helper
Loading Splice Connect module
Splice Connect Module loaded {
  connectMethods: [
    'startServer',
    'setConnectEnabled',
    'sendError',
    'broadcastGenericMessage',
    'triggerStatefulSubscriptions',
    'loadSample',
    'loadPreset',
    'registerPreviousAssetHandler',
    'registerNextAssetHandler',
    'registerPurchaseAssetHandler',
    'registerSessionHandler',
    'registerDevicesHandler',
    'registerClientConnectHandler',
    'registerErrorHandler',
    'registerGenericMessageHandler',
    'assetPurchased'
  ]
}
15:13:07.807 [INFO] [pid=1164] ui-main - ConnectManager: initializeSpliceConnect() [Function (anonymous)]
15:13:07.808 [INFO] [pid=1164] ui-main - ConnectManager: Splice Connect SDK Server started
15:13:07.808 [INFO] [pid=1164] ui-main - Starting Splice Helper: "/Applications/Splice.app/Contents/Resources/Splice Helper.app/Contents/MacOS/Splice Helper" -pid 1164 -electronPort 57766
[1164:0410/151308.000249:ERROR:gpu_process_host.cc(962)] GPU process exited unexpectedly: exit_code=9
15:13:08.006 [INFO] [pid=1164] ui-main - VstManager Received Bridge version compatibility update. Is compatible: true
15:13:08.006 [ERROR] [pid=1164] ui-main - initVstConnection(): no port passed in and no saved port!
15:13:08.006 [INFO] [pid=1164] ui-main - UI not ready, enqueueing message...
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error: ENOENT: no such file or directory, scandir '/var/folders/yq/khmf7sv53_56512yxkcdg5g80000gn/T/splice'
15:13:08.113 [INFO] [pid=1164] ui-main - ConnectManager: Splice Connect SDK SessionHandler {
  assetType: 'preset',
  deviceId: '',
  instanceId: '',
  state: 1,
  doSearch: false
}
15:13:08.113 [INFO] [pid=1164] ui-main - UI not ready, enqueueing message...
15:13:08.113 [INFO] [pid=1164] ui-main - ConnectManager: Splice Connect SDK DevicesHandler { deviceIds: [] }
15:13:08.113 [INFO] [pid=1164] ui-main - UI not ready, enqueueing message...
15:13:08.113 [INFO] [pid=1164] ui-main - ConnectManager: Splice Connect SDK ClientConnectHandler { deviceId: '', instanceId: '', state: 3 }
15:13:08.113 [INFO] [pid=1164] ui-main - UI not ready, enqueueing message...
15:13:08.114 [INFO] [pid=1164] ui-main - Bridge gRPC server created on port 57765
[1164:0410/151308.115750:ERROR:network_service_instance_impl.cc(333)] Network service crashed, restarting service.
15:13:08.166 [INFO] [pid=1164] ui-main - VstManager Received Bridge version compatibility update. Is compatible: false
15:13:08.167 [INFO] [pid=1164] ui-main - UI not ready, enqueueing message...
15:13:08.200 [INFO] [pid=1174] core/main - Initializing client (ui_pid: 1164) (parent_pid: 1164) (build_version: 5.0.11) 
15:13:08.200 [INFO] [pid=1174] core/main - Found DAW installation (location: /Applications/Logic Pro X.app) (bits: 64) (filehash: 65e439d37bed580d4d29d3d1980d97ef8e616c72) (name: Logic) (version: 10.7.6 (5754)) 
15:13:08.200 [INFO] [pid=1174] core/main - Found DAW installation (bits: 64) (filehash: 20aff28c547edcbc87db5b697ec157afccf9fc09) (name: Ableton Live) (version: 11.3.4 (2023-06-27_d83675ef81)) (location: /Applications/Ableton Live 11 Suite.app) 
15:13:08.200 [INFO] [pid=1174] core/api-client - API client is configured (machine_id: 4B83F5E2-CF57AADA-ED557829-809EFEC7) (env: default) 
15:13:08.201 [INFO] [pid=1174] core/server - Listening on (address: 127.0.0.1:56765) 
15:13:08.207 [INFO] [pid=1174] core/main - Helper sent start message to Electron (info: message:"Hello, 56765") 
15:13:08.209 [INFO] [pid=1174] core/telemetry - Sending event to bus (action: Client opened) (props: map[]) 
15:13:08.209 [INFO] [pid=1174] core/main - Watching UI process for exit (parent_pid: 1164) 
15:13:08.215 [INFO] [pid=1174] core/server - StreamEvents: stream starting (stream: &{0xc0002d8000}) 
15:13:08.217 [INFO] [pid=1164] ui-main - Connected to bridge { host: '127.0.0.1', port: 56765 }
15:13:08.217 [INFO] [pid=1164] ui-main - UI not ready, enqueueing message...
15:13:08.527 [INFO] [pid=1174] core/reachability - Network connected. 
15:13:08.527 [WARN] [pid=1174] core/pubsub - Failed to start pubsub, user is not ready 
15:13:08.527 [INFO] [pid=1164] ui-main - UI not ready, enqueueing message...
[1164:0410/151308.619897:ERROR:network_service_instance_impl.cc(333)] Network service crashed, restarting service.
info: [LaunchDarkly] LaunchDarkly client initialized
[1164:0410/151308.945173:ERROR:gpu_process_host.cc(962)] GPU process exited unexpectedly: exit_code=9
15:13:08.957 [INFO] [pid=1164] ui-main - Closing auth-only LaunchDarkly client
deactivating splice auth manager
15:13:09.156 [INFO] [pid=1164] ui-main - deactivating offline auth manager
15:13:09.157 [INFO] [pid=1164] ui-main - activating auth0 auth manager
15:13:09.157 [INFO] [pid=1164] ui-main - UI not ready, enqueueing message...
sysctl: unknown oid 'sysctl.proc_translated'
15:13:09.336 [INFO] [pid=1164] ui-main - User-Agent Splice Baelish/darwin/x64/x64 5.0.11/15d8d297/stable
[1164:0410/151309.338202:ERROR:network_service_instance_impl.cc(333)] Network service crashed, restarting service.
sysctl: unknown oid 'sysctl.proc_translated'
15:13:09.545 [INFO] [pid=1164] ui-main - Unable to retrieve access token from stored refresh token FetchError: request to https://auth.splice.com/oauth/token failed, reason: net::ERR_FAILED
    at ClientRequest.<anonymous> (/Applications/Splice.app/Contents/Resources/app.asar/node_modules/electron-fetch/lib/index.js:1402:14)
    at ClientRequest.emit (events.js:388:22)
    at ClientRequest.emit (domain.js:470:12)
    at ClientRequest._die (electron/js2c/browser_init.js:105:8391)
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:7128)
    at SimpleURLLoaderWrapper.emit (events.js:376:20)
    at SimpleURLLoaderWrapper.emit (domain.js:470:12) {
  type: 'system',
  errno: 'ERR_FAILED',
  code: 'ERR_FAILED'
}
15:13:09.546 [INFO] [pid=1164] ui-main - signin: signing in
(node:1164) electron: The default of nativeWindowOpen is deprecated and will be changing from false to true in Electron 15.  See https://github.com/electron/electron/issues/28511 for more information.
[1164:0410/151309.632840:ERROR:gpu_process_host.cc(962)] GPU process exited unexpectedly: exit_code=9
[1164:0410/151310.213194:ERROR:gpu_process_host.cc(962)] GPU process exited unexpectedly: exit_code=9
[1164:0410/151310.735081:ERROR:gpu_process_host.cc(962)] GPU process exited unexpectedly: exit_code=9
[1164:0410/151311.260198:ERROR:gpu_process_host.cc(962)] GPU process exited unexpectedly: exit_code=9
[1164:0410/151311.736570:ERROR:gpu_process_host.cc(962)] GPU process exited unexpectedly: exit_code=9
15:13:14.601 [INFO] [pid=1164] ui-main - Started auto-update check at 'https://api.splice.com/v2/desktop/darwin/stable/latest?v=5.0.11&architecture=x64' every 3600 sec.
15:13:14.612 [INFO] [pid=1164] ui-main - Checking for update.
[1164:0410/151314.615407:ERROR:network_service_instance_impl.cc(333)] Network service crashed, restarting service.
15:13:15.032 [INFO] [pid=1164] ui-main - Update available.
[1164:0410/151315.338167:ERROR:network_service_instance_impl.cc(333)] Network service crashed, restarting service.
[1164:0410/151315.481023:ERROR:gpu_process_host.cc(962)] GPU process exited unexpectedly: exit_code=9
[1164:0410/151315.767790:ERROR:network_service_instance_impl.cc(333)] Network service crashed, restarting service.
[1164:0410/151316.204263:ERROR:gpu_process_host.cc(962)] GPU process exited unexpectedly: exit_code=9
[1164:0410/151316.204298:FATAL:gpu_data_manager_impl_private.cc(414)] GPU process isn't usable. Goodbye.
zsh: illegal hardware instruction

**Comment by bennydf123** [comment]
Did you find a solution to the problem?

**Comment by bennydf123** [comment]
SOLVED!!

For this release for the hack to load up as is (without wifi solved in other threads in the post) add the following boot args. amfi=0x80 and ipc_control_port_options=0 which fixes any apps using Electron as a build (this promted the error message exit_code=9 and didn't engage hardware acceleration).
